### ISSUE TITLE
Apparent crash upon opening OpenBlocks book

### ISSUE THREAD

**Issue by TheOnlyQueue** [Carbon-Quadoxide-Initiative/Cat#1]
Need to investigate

**Comment by mr10movie** [comment]
I have looked into it before. Nobody on IRC said anything, and no updates have fixed anything.

**Comment by TheOnlyQueue** [comment]
hmmm

**Comment by mr10movie** [comment]
> **@boq** you either have old version of mod or disabled recipes

Dammit, I'm gonna try something.
