### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by SpectacularNumbers** [Carbon-Quadoxide-Initiative/Cat#3]
Hello,
Unless you have permissions from the mod developers you can not rehost the mods on git, you can only post a modlist.

**Comment by TheOnlyQueue** [comment]
This is slightly different, but I will take a look into that.

On Sun, Feb 1, 2015 at 3:30 PM, SpectacularNumbers <notifications@github.com

> wrote:
> 
> Hello,
> Unless you have permissions from the mod developers you can not rehost the
> mods on git, you can only post a modlist.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Carbon-Quadoxide-Initiative/Cat/issues/3.

## 

---

J Calkins

**Comment by TheOnlyQueue** [comment]
Nice modpack, by the way. I'll see if we can sort it out like yours.The
issue is making a modpack with multiple people without GitHub and without
paying for a private repo.

On Sun, Feb 1, 2015 at 3:43 PM, J Calkins jsc.cub@gmail.com wrote:

> This is slightly different, but I will take a look into that.
> 
> On Sun, Feb 1, 2015 at 3:30 PM, SpectacularNumbers <
> notifications@github.com> wrote:
> 
> > Hello,
> > Unless you have permissions from the mod developers you can not rehost
> > the mods on git, you can only post a modlist.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Carbon-Quadoxide-Initiative/Cat/issues/3.
> 
> ## 
> 
> ---
> 
> J Calkins

## 

---

J Calkins

**Comment by Nincodedo** [comment]
BitBucket has free private repos.

**Comment by TheOnlyQueue** [comment]
I thought they were paid? If so, thank you very much for the heads up.

On Sun, Feb 1, 2015 at 4:13 PM, Nincodedo notifications@github.com wrote:

> BitBucket has free private repos.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Carbon-Quadoxide-Initiative/Cat/issues/3#issuecomment-72384498
> .

## 

---

J Calkins

**Comment by TheOnlyQueue** [comment]
Now the question is, what is the BitBucket equivalent of the Git Windows client?

**Comment by mr10movie** [comment]
https://blog.bitbucket.org/2013/03/19/introducing-sourcetree-git-client-microsoft-windows/ ?

**Comment by TheOnlyQueue** [comment]
Awesome

**Comment by SpectacularNumbers** [comment]
If you also would like, I could create a modlist like the one I have for my modpack. (https://github.com/SpectacularNumbers/Worlds/blob/master/mods/modlist.txt)

**Comment by TheOnlyQueue** [comment]
Thanks, I saw how you did that and it looks pretty nice, but I talked to some of the FTB 3rd party pack team and they said to just ensure we had a permissions.txt in the /mods folder. I'll probably go with that, and just remove fastcraft (the PM for permissions on that is talking a wee bit longer than expected). Thank you for the offer though.
